TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

#----------------------------------------------------
#  Optimization of db files using dbst (DEFAULT: NO)
#DB_OPT = YES

#----------------------------------------------------
# Create and install (or just install) into <top>/db
# databases, templates, substitutions like this
DB += AS503_Chan.template
DB += AS505_Chan.template
DB += HVgroup.template
DB += CaenHV_crate1.substitutions
DB += CaenHV_crate2.substitutions
DB += CaenHV_crate3.substitutions
DB += CaenHV_crate4.substitutions
DB += CaenHV_crate5.substitutions
DB += CaenHV_crate11.substitutions
DB += CaenHV_crate12.substitutions
DB += CaenHV_Test.substitutions

USES_TEMPLATE += AS503_Chan.template
USES_TEMPLATE += AS505_Chan.template
USES_TEMPLATE += HVgroup.template

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

